name: "resume"
services:
  vue:
    hostname: vue
    stdin_open: true
    tty: true
    build:
      context: .docker
      dockerfile: node.dockerfile
    command: bash -c "pnpm install && pnpm run dev --host"
    #command: bash -c 'sleep 3600'
    volumes:
      - .:/app:rw
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"

  nginx:
    hostname: nginx
    stdin_open: true
    tty: true
    build:
      context: .docker
      dockerfile: nginx.dockerfile
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "443:443"
